### ISSUE TITLE
U+2639 Frowning Face Emoji renders incorrectly on Android

### ISSUE THREAD

**Issue by emesterhazy** [Fintasys/emoji_picker_flutter#171] opened 2023-11-24 18:37 UTC
The [frowning face](https://github.com/Fintasys/emoji_picker_flutter/blob/0a206b60e6b6a431b886081b94713ab8547d1b97/lib/src/default_emoji_set.dart#L81C12-L81C13) emoji does not render correctly on Android, even though typical Android fonts such as `Noto Color Emoji` support it.

<img width="424" alt="Screenshot 2023-11-24 at 10 57 07" src="https://github.com/Fintasys/emoji_picker_flutter/assets/26512665/00673c7e-a6b7-429a-a1f8-b8aa47f2b8e6">

Another dev reported this issues ~2 years ago, but it was closed because technically users can override the default fonts in order to get the emoji to work.

I haven't found a solution yet that works without importing Google Fonts, which shouldn't be necessary. In theory specifying `Noto Color Emoji` or `NotoColorEmoji` should work, but it didn't when I tried it in the Android simulator.

**Comment by emesterhazy** [comment] 2024-01-04 21:33
Coming into this I assumed that Android bundled Noto Color Emoji, or at least that Pixel phones would include it. I still suspect that this is true, but maybe for some reason Flutter isn't able to access it. I don't know enough about how Flutter and Android handle fonts to say either way. I just doubt that every Android app that uses emojis is forced to bundle an emoji font. That would be madness.

**Comment by Fintasys** [comment] 2024-01-05 00:59
Yes I agree and that's probably that's the case, Flutter apps must not able to access the native fonts for some reason. I will continue to keep my eyes open for an explanation or solution.

**Comment by emesterhazy** [comment] 2024-01-06 17:48
I asked a question on the Flutter repo since after searching for a while this morning I wasn't able to find any documentation explaining how Flutter interacts with system fonts. Hopefully someone can clarify.

- https://github.com/flutter/flutter/issues/48381#issuecomment-1879766322

**Comment by Fintasys** [comment] 2024-01-10 23:59
@emesterhazy Good news! I was told by another Flutter dev that this issue is solved from 3.18 and I could confirm it with current beta that the frowning face and others are being rendered correctly! 🤩 Not sure which exact commit did it, tho. 
![Screenshot_1704931098](https://github.com/Fintasys/emoji_picker_flutter/assets/11667234/bcb937a5-2595-4913-927a-dc7f334b5b12)

**Comment by Fintasys** [comment] 2024-02-28 13:17
Since Flutter 3.19 has been released and the issue is solved, I think we can close this issue 🙏 Thanks for your help !

**Closed by Fintasys** 2024-02-28 13:17 UTC
