### ISSUE TITLE
Controller's length property (9) does not match the number of tabs (17) present in TabBar's tabs property

### ISSUE THREAD

**Issue by worldwidee** [Fintasys/emoji_picker_flutter#120] opened 2022-12-15 14:50 UTC
![Ekran Alıntısı](https://user-images.githubusercontent.com/49057380/207890995-4174f51b-abbd-45e4-b3cc-92f0388eb687.JPG)
![Ekran Alıntısı2](https://user-images.githubusercontent.com/49057380/207891191-0fb5792b-26ec-4e4c-afb8-0d490a85ce4b.JPG)

Sometimes I'am having this issue when i view emoji picker.

**Comment by LostInDarkMath** [comment] 2023-01-05 07:46
Duplicate of https://github.com/Fintasys/emoji_picker_flutter/issues/106

**Comment by Fintasys** [comment] 2023-01-12 11:13
Thx @LostInDarkMath I will close this issue for now. If the solution mentioned in above's duplicate doesn't help please open another issue @worldwidee

**Closed by Fintasys** 2023-01-12 11:13 UTC
