### ISSUE TITLE
Duplicated categories tabs

### ISSUE THREAD

**Issue by EsteveAguilera** [Fintasys/emoji_picker_flutter#12] opened 2021-05-13 09:18 UTC
Using version `emoji_picker_flutter: ^1.0.4`  I've got duplicated categories tabs.

![image](https://user-images.githubusercontent.com/6932449/118105599-df920d80-b3dc-11eb-992a-5f66ba88b27e.png)

I've not been able to reproduce it a second time 🤷

**Comment by Fintasys** [comment] 2021-05-13 15:04
@EsteveAguilera Thanks for reporting this issue ! First time I hear about this issue, please let me know if it happens again.  I will check if can find something.

**Comment by rocboronat** [comment] 2021-05-18 11:28
Yey! Just happened to mee too. We're working together on the same app, hehe... It happened when pushing a new screen on the one that shows the emoji, and then pop it. When rebuilding the tree, the keyboard shown the categories duplicated.

Maybe there's a race condition?

**Comment by Fintasys** [comment] 2021-05-18 14:40
Good to have a way to replicate bugs, thanks for sharing. You both are keeping me busy 🤣 Feel free to investigate into the issues as well, I'm currently lacking a bit of time. 🙏

**Comment by Fintasys** [comment] 2021-05-30 02:08
I've tried to reproduce again because it also happened to me in the past when I did hot reload. But also with the steps above I couldn't reproduce it in current version. I doubt that it is gone but I will keep an eye on it

**Comment by rocboronat** [comment] 2021-05-30 20:19
Oh! 😲

Maybe it happened because of the hot reload! If you want to, close the issue. If it happens again on the production app we will share it again so you can reopen the issue. Hope it never happens again! 😄

Thanks for your time, @Fintasys 😊

**Comment by rocboronat** [comment] 2021-07-14 16:23
Some months later I didn't see it happening again... So I close the issue. If it happens again, I'll reopen it or open a new one. Thanks for the support! 🙇

**Comment by rocboronat** [comment] 2021-07-14 16:23
Oh, I don't have permissions to close issues, haha!

**Comment by rocboronat** [comment] 2021-07-27 09:00
Hey! It happened on release mode. And after closing the keyboard and opening it again, it was fixed :·/ Weird. @Fintasys may you reopen the issue?

**Comment by Fintasys** [comment] 2021-07-27 09:09
@rocboronat even in release mode? That's not good 😅 I would appreciate help, otherwise I will look into the issue when I find time 🙇

**Comment by rocboronat** [comment] 2021-07-27 09:13
Zeeero hurries, of course! It's not something that happens a lot. I will take a look into it if I have time. Maybe after we released our new Flutter app! 🚀 

Thanks a lot for your time 😄

**Comment by rocboronat** [comment] 2021-08-18 23:00
It happened again! It's so weird it doesn't duplicate the first two tabs, as @EsteveAguilera shows in his screenshot.

**Comment by Fintasys** [comment] 2021-08-22 15:47
@rocboronat I've fixed some bugs and enable hot reload support for this library. Hopefully rebuilding the Widget completely when the state is dirty should fix this issue 🙏

**Comment by rocboronat** [comment] 2021-08-22 16:47
Ooooh thanks! If you want us to test it on producton as brave people do, count with us 😄

**Comment by Fintasys** [comment] 2021-08-23 08:10
@rocboronat I'll leave that up to you 😆 I gonna release the changes soon on pub.dev if there aren't any issues reported in dev. But I'm curious about you App if it's already public, would love to see my picker in a production App 😄

**Comment by rocboronat** [comment] 2021-08-23 08:13
It's not public yet... you'll be the first one to know it when we release it! It the meantime, it's called QuitNow. We're replacing the published one, a native Android, with a Flutter one 😊

**Comment by Fintasys** [comment] 2021-08-23 08:24
Awesome ! Gotta wait and start smoking beforehand to have an actual use case 😆

**Comment by rocboronat** [comment] 2021-08-23 22:21
Hahaha! That's braver than testing on production! 😂

**Comment by rocboronat** [comment] 2021-09-06 11:51
We're almost on production! Buuut the latest version of the app also has the issue. In a different way, though! It's funny :·)

![photo_2021-09-06_13-50-34](https://user-images.githubusercontent.com/456499/132213314-a8f56039-6011-4984-aff7-de7c8aa264d5.jpg)

**Comment by Fintasys** [comment] 2021-09-06 14:15
@rocboronat Argh, limited funny 😄  But at least now it repeats the whole category list and not every category icon twice. Might be a hint to locate the problem

**Comment by Fintasys** [comment] 2021-09-13 07:23
@EsteveAguilera @rocboronat Could you take a quick loot at this PR? I tried again to address this issue and would like to hear your opinion. https://github.com/Fintasys/emoji_picker_flutter/pull/25 Thank you!

**Closed** 2021-09-27 13:35 UTC
Labels: bug, monitor

**Comment by verhneudinec** [comment] 2022-09-13 03:49
Hi, @Fintasys! Duplication remains. It is reproduced during a clean installation of the release or profile build of the application (Flutter 3.3.0) :(

Temporarily, passing a key (UniqueKey) to EmojiPicker may help.
