### ISSUE TITLE
categoryIcons become more and overlap

### ISSUE THREAD

**Issue by yjr-1100** [Fintasys/emoji_picker_flutter#126] opened 2023-02-06 09:28 UTC
My local environment is **flutter3.3.9**, **Dart 2.18.3**, and the version of the package **1.5.2**. 

When the display state of emojipicker is switched repeatedly when the keyboard pops up, the following picture will appear

categoryIcons become more and overlap

![qq_pic_merged_1675674936388](https://user-images.githubusercontent.com/55343957/216934704-b918a486-85ed-402e-8fa9-1ca8fbb93d1f.jpg)

**Comment by Fintasys** [comment] 2023-02-11 06:00
Duplicate of #106

**Closed** 2023-02-16 06:20 UTC
