### ISSUE TITLE
Don't attach Emoji to TextEditingController until call setstate

### ISSUE THREAD

**Issue by Zeinab-Kouhkan** [Fintasys/emoji_picker_flutter#217] opened 2024-09-28 12:41 UTC
When use emoji picker , I need call setstate for attach emoji to textEditingController.
this is my code:
```
import 'package:emoji_picker_flutter/emoji_picker_flutter.dart';
import 'package:flutter/material.dart';
import 'package:universal_io/io.dart';
import 'package:zireh/base/resourceful_state.dart';
import 'package:zireh/screens/chat/provider.dart';
import 'package:zireh/utils/image.dart';
import 'package:zireh/widgets/sized_box/space.dart';

import '../../themes/colors.dart';
import '../../themes/shapes.dart';
import 'bloc.dart';

class ChatInputArea extends StatefulWidget {
  const ChatInputArea(this.onSendMessageClickCallback, {super.key});

  final Function() onSendMessageClickCallback;

  @override
  State<ChatInputArea> createState() => _ChatInputAreaState();
}

class _ChatInputAreaState extends ResourcefulState<ChatInputArea> {
  late FocusNode inputFocusNode;
  late TextEditingController inputController;
  late ChatBloc bloc;
  late bool enableSendButton;
  late ScrollController _scrollController;

  @override
  void initState() {
    super.initState();
    inputFocusNode = FocusNode();
    inputController = TextEditingController();
    _scrollController = ScrollController();
  }

  @override
  void dispose() {
    inputFocusNode.dispose();
    inputController.dispose();
    _scrollController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    super.build(context);
    bloc = ChatProvider.of(context);
    return Container(
        decoration: AppDecorations.boxTopLarge.copyWith(
          color: AppColors.colors.onPrimary,
          boxShadow: [
            BoxShadow(
              color: AppColors.colors.shadowChatInputBox,
              // Equivalent to #0000001A
              offset: const Offset(0, 5),
              // x and y offsets
              blurRadius: 30,
              // Blur radius
              spreadRadius: 0, // Spread radius
            ),
          ],
        ),
        margin: EdgeInsets.zero,
        padding: EdgeInsets.symmetric(vertical: 0.5.h),
        child: Column(
          children: [inputRowData(), emoji()],
        ));
  }

  Widget inputRowData() {
    return inputField();
  }

  Widget inputField() {
    return TextField(
      onChanged: (text) {

        bloc.onInputTextChanged(text);
      },
      onTap: () => bloc.onEmojiClick(showEmoji: false),
      controller: inputController,
      focusNode: inputFocusNode,
      textAlignVertical: TextAlignVertical.top,
      keyboardType: TextInputType.multiline,
      cursorColor: AppColors.colors.secondary,
      expands: false,
      minLines: 1,
      maxLines: null,
      decoration: InputDecoration(
          filled: true,
          fillColor: AppColors.colors.scaffold,
          labelText: intl.jotDownYourMessage,
          contentPadding: EdgeInsets.symmetric(horizontal: 4.w, vertical: 2.h),
          labelStyle: typography.bodySmall?.apply(
            color: AppColors.colors.subtitleText,
          ),
          isDense: true,
          floatingLabelBehavior: FloatingLabelBehavior.never,
          focusColor: AppColors.colors.onPrimary,
          focusedBorder: AppOutlineInputBorder.borderMild.copyWith(
            borderSide: BorderSide(color: AppColors.colors.onPrimary),
          ),
          enabledBorder: AppOutlineInputBorder.borderMild.copyWith(
            borderSide: BorderSide(color: AppColors.colors.onPrimary),
          ),
          prefixIcon: prefixButton(),
          suffixIcon: suffixButton(),
          suffixIconConstraints: BoxConstraints(maxWidth: 11.w),
          prefixIconConstraints: BoxConstraints(maxWidth: 20.w)),
      style: typography.titleMedium,
    );
  }

  Widget prefixButton() {
    return Padding(
      padding: EdgeInsets.only(right: 4.w),
      child: StreamBuilder<bool>(
          stream: bloc.sendButtonEnabled,
          builder: (context, snapshot) {
            return snapshot.data == true
                ? GestureDetector(
                    onTap: () {
                      inputController.clear();
                      bloc.onSendMessageClick();
                      widget.onSendMessageClickCallback();
                    },
                    //todo: If you intent to add recorder uncomment below code
                    /*        onLongPress: () {
                      bloc.record();
                      enableGlow = true;
                      setState(() {});
                    },
                    onLongPressUp: () {
                      enableGlow = false;
                      bloc.stopRecorder();
                      setState(() {});
                    },*/
                    child: ImageUtils.fromLocal(
                        'assets/icon/enable_send_button.svg',
                        width: 7.w),
                  )
                : Row(
                    children: [
                      GestureDetector(
                        onTap: () {
                          inputFocusNode.unfocus();
                          inputFocusNode.canRequestFocus = false;
                          bloc.onAttachmentClick();
                          Future.delayed(const Duration(milliseconds: 100), () {
                            inputFocusNode.canRequestFocus = true;
                          });
                        },
                        child: ImageUtils.fromLocal('assets/icon/attach1.svg',
                            width: 6.4.w, height: 6.4.w),
                      ),
                      Space(
                        width: 3.w,
                      ),
                      ImageUtils.fromLocal('assets/icon/mic1.svg',
                          width: 6.4.w, height: 6.4.w),
                    ],
                  );
          }),
    );
  }

  Widget suffixButton() {
    return Padding(
      padding: EdgeInsets.only(left: 4.w),
      child: StreamBuilder<bool>(
          stream: bloc.sendButtonEnabled,
          builder: (context, snapshot) {
            return snapshot.data != true
                ? ImageUtils.fromLocal('assets/icon/disable_send_button.svg',
                    width: 7.w)
                :  GestureDetector(
                    onTap: bloc.onEmojiClick,
                    child: StreamBuilder<bool>(
                        stream: bloc.showEmoji,
                        builder: (context, snapshot) {
                          return snapshot.data != true
                              ? ImageUtils.fromLocal('assets/icon/emoji.svg',
                                  width: 6.4.w, height: 6.4.w)
                              : ImageUtils.fromLocal(
                                  'assets/icon/close_circle_label.svg',
                                  width: 6.4.w,
                                  height: 6.4.w);
                        }),
                  ) ;
          }),
    );
  }

  Widget emoji() {
    return StreamBuilder<bool>(
        stream: bloc.showEmoji,
        builder: (context, snapshot) {
          if (snapshot.data == true) {
            FocusScope.of(context).unfocus();
          }
          return Offstage(
            offstage: snapshot.data != true,
            child: EmojiPicker(
              textEditingController: inputController,
              scrollController: _scrollController,
              config: Config(
                height: 26.h,
                checkPlatformCompatibility: true,
                emojiViewConfig: EmojiViewConfig(
                  gridPadding:
                      EdgeInsets.symmetric(horizontal: 2.w, vertical: 1.h),
                  emojiSizeMax: 28 * (Platform.isIOS ? 1 : 0.8),
                ),
                swapCategoryAndBottomBar: true,
                skinToneConfig:
                    SkinToneConfig(indicatorColor: AppColors.colors.secondary),
                categoryViewConfig: CategoryViewConfig(
                    iconColorSelected: AppColors.colors.secondary,
                    indicatorColor: AppColors.colors.secondary),
                bottomActionBarConfig: BottomActionBarConfig(
                    enabled: false,
                    showBackspaceButton: true,
                    backgroundColor: Colors.transparent,
                    buttonColor: AppColors.colors.secondary),
                searchViewConfig: const SearchViewConfig(),
              ),
            ),
          );
        });
  }
}

```

**Comment by Fintasys** [comment] 2024-11-10 22:46
@Zeinab-Kouhkan Sorry for the late response, is this issue still ongoing or were you able to fix it?

**Comment by Fintasys** [comment] 2024-11-15 07:11
Here is an AI generated answer, cause the issue is not within the package, but likely the way you using it. Please create another issue with more information if the issue persist 🙏 :

You don't need to explicitly call `setState` when using `textEditingController` with the` emoji_picker_flutter` package. The EmojiPicker widget automatically updates the TextEditingController's text when an emoji is selected. The TextField widget listens to changes in the controller and rebuilds itself accordingly.

The issue likely lies elsewhere in your code. Here's a breakdown of potential problems and solutions, along with a refined code snippet:

Potential Problems and Solutions:

1. **bloc.showEmoji Stream Not Updating:** The Offstage widget relies on the bloc.showEmoji stream. If this stream isn't updating correctly when you select an emoji or close the picker, the Offstage widget won't rebuild, and you won't see the changes. Ensure that your bloc.onEmojiClick function properly updates the showEmoji stream.

2. **Focus Issues:** Sometimes focus issues can interfere with the UI updates. Try adding FocusScope.of(context).unfocus(); before showing the emoji picker and requesting focus back to the TextField after closing the emoji picker.

2. **Incorrect EmojiPicker Configuration:** Ensure the EmojiPicker is correctly configured and attached to the TextEditingController. You've done this correctly in the provided code, but double-check it.

Refined Code Snippet:

```
import 'package:emoji_picker_flutter/emoji_picker_flutter.dart';
import 'package:flutter/material.dart';
// ... other imports

class ChatInputArea extends StatefulWidget { // ... }

class _ChatInputAreaState extends ResourcefulState<ChatInputArea> {
  // ... (Existing code)

  Widget emoji() {
    return StreamBuilder<bool>(
        stream: bloc.showEmoji,
        builder: (context, snapshot) {
          bool showEmoji = snapshot.data ?? false; // Handle null snapshot data

          return Offstage(
            offstage: !showEmoji, // Simplified condition
            child: SizedBox( // Wrap with SizedBox for better layout control
              height: showEmoji ? 26.h : 0,  // Dynamic height based on visibility
              child: EmojiPicker(
                textEditingController: inputController,
                scrollController: _scrollController,
                config: Config(
                  // ... (Your existing Config)
                ),
                onEmojiSelected: (category, emoji) { // Callback for debugging
                  print('Emoji selected: $emoji');
                },
              ),
            ),
          );
        });
  }


  Widget suffixButton() {
    return Padding(
      padding: EdgeInsets.only(left: 4.w),
      child: StreamBuilder<bool>(
        stream: bloc.sendButtonEnabled,
        builder: (context, snapshot) {
          bool isEnabled = snapshot.data ?? false;
          return GestureDetector( // Wrap with GestureDetector even when disabled
            onTap: () {
              if (!isEnabled) return; // Do nothing if disabled

              // Manage focus and show/hide emoji picker
              if (bloc.showEmojiValue) {
                bloc.onEmojiClick(showEmoji: false);
                FocusScope.of(context).requestFocus(inputFocusNode); // Return focus to text field
              } else {
                FocusScope.of(context).unfocus();
                bloc.onEmojiClick(showEmoji: true);
              }

            },
            child: StreamBuilder<bool>(
                stream: bloc.showEmoji,
                builder: (context, snapshot) {
                  bool showEmoji = snapshot.data ?? false;
                  return showEmoji
                        ? ImageUtils.fromLocal(
                            'assets/icon/close_circle_label.svg',
                            width: 6.4.w,
                            height: 6.4.w)
                        :ImageUtils.fromLocal('assets/icon/emoji.svg',
                              width: 6.4.w, height: 6.4.w) ;
                }),
          );
        },
      ),
    );
  }

  // ... (Rest of your code)
}
```

If the issue persists, please provide the implementation of your ChatBloc and how you are updating the showEmoji stream within onEmojiClick so I can give you more tailored assistance. Also, check your Flutter version and ensure the emoji_picker_flutter package is up-to-date.

**Closed by Fintasys** 2024-11-15 07:11 UTC
